steps:
  - label: ":docker: create base image"
    command: 
      - ".buildkite/steps/build-builder.sh"
      - ".buildkite/steps/upload-builder.sh"
    timeout: 60

  - wait

  - label: ":docker: build docker image"
    command:
      - ".buildkite/steps/build-image.sh"
      - ".buildkite/steps/upload-image.sh"

  - wait

  - label: ":cop::skin-tone-2: deploy check"
    command: ".buildkite/steps/deploy-test.sh"
    timeout: 20

  - label: ":cop::skin-tone-2: api test"
    command: ".buildkite/steps/api-test.sh"
    timeout: 20

  - label: ":cop::skin-tone-2: unit_test"
    command: ".buildkite/steps/deploy-unit_test.sh"

  - wait

  - label: ":floppy_disk: upload base image"
    command: ".buildkite/steps/publish-builder.sh"
    branches: "master alfa develop ci-* v*.*.*"

  - wait

  - label: ":floppy_disk: upload image"
    command: ".buildkite/steps/publish-image.sh"
    branches: "master alfa develop ci-* v*.*.*"

  - wait

  - label: ":docker: mongodb-exporter"
    command: ".buildkite/steps/mongodb-exporter.sh"
    branches: "master"
    timeout: 20

  - wait

  - label: ":slack:"
    command: ".buildkite/steps/slack.sh \"Pipeline complete successfully: ${BUILDKITE_MESSAGE}\" \"good\""
