steps:
  - label: ":pipeline: run build steps"
    trigger: "build-only-cyberway-image"
    build:
        message: "${BUILDKITE_MESSAGE}"
        commit: "${BUILDKITE_COMMIT}"
        branch: "${BUILDKITE_BRANCH}"
        env:
           BUILDKITE_PULL_REQUEST: "${BUILDKITE_PULL_REQUEST}"
           BUILDKITE_PULL_REQUEST_BASE_BRANCH: "${BUILDKITE_PULL_REQUEST_BASE_BRANCH}"
           BUILDKITE_PULL_REQUEST_REPO: "${BUILDKITE_PULL_REQUEST_REPO}"

  - wait

  - label: ":pipeline: run test steps"
    trigger: "test-only-cyberway-image"
    build:
        message: "${BUILDKITE_MESSAGE}"
        commit: "${BUILDKITE_COMMIT}"
        branch: "${BUILDKITE_BRANCH}"
        env:
           BUILDKITE_PULL_REQUEST: "${BUILDKITE_PULL_REQUEST}"
           BUILDKITE_PULL_REQUEST_BASE_BRANCH: "${BUILDKITE_PULL_REQUEST_BASE_BRANCH}"
           BUILDKITE_PULL_REQUEST_REPO: "${BUILDKITE_PULL_REQUEST_REPO}"


  - wait

  - label: ":floppy_disk: upload base image"
    command: ".buildkite/steps/publish-builder.sh"
    branches: "master alfa develop ci-* v*.*.*"

  - wait

  - label: ":floppy_disk: upload image"
    command: ".buildkite/steps/publish-image.sh"
    branches: "master alfa develop ci-* v*.*.*"

  - wait

  - label: ":docker: mongodb-exporter"
    command: ".buildkite/steps/mongodb-exporter.sh"
    branches: "master"
    timeout: 20
    